---

- hosts: sandbox
  remote_user: root
  sudo: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml
  roles:
    - python-base
    - wsgi-app
    - uwsgi
    - supervisor
    - nginx
