---

- hosts: sandbox
  remote_user: root
  sudo: yes
  roles:
    - python-base
    - python-app
    - gunicorn
    - supervisor
    - nginx
  vars:
    app_name: servator
    git_repo: git@bitbucket.org:janitor/servator.git

    gunicorn_user: "{{ app_name }}"
    gunicorn_group: webapps

    virtualenv_path: "/webapps/{{ app_name }}"
    serve_directory_path: "{{ virtualenv_path }}/serve"
    project_path: "{{ virtualenv_path }}/{{ app_name }}"
    application_log_dir: "{{ virtualenv_path }}/logs"
    application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
    requirements_file: "{{ project_path }}/requirements.txt"

    nginx_server_name_re: ~^(?<subdomain>[a-z0-9]+)\.servator\.ws
    nginx_upload_server_name_re: ~^servator\.ws www.servator.ws ""
    nginx_port: 80
    nginx_client_max_body_size: 20M

    nginx_web_access_log_file: "{{ application_log_dir }}/nginx_web_access.log"
    nginx_web_error_log_file: "{{ application_log_dir }}/nginx_web_error.log"

    nginx_serve_access_log_file: "{{ application_log_dir }}/nginx_serve_access.log"
    nginx_serve_error_log_file: "{{ application_log_dir }}/nginx_serve_error.log"

    redis_host: localhost
    redis_port: 6379
#    setup_git_repo: yes
    git_branch: master

    gunicorn_max_requests: 20
    wsgi_app: "app:app"
