---

- name: Adding APT repository key
  apt_key:
    url: "http://nginx.org/keys/nginx_signing.key"

- name: Add official APT repository
  when: ansible_os_family == 'Debian'
  sudo: yes
  apt_repository:
    repo: "deb http://nginx.org/packages/{{ansible_distribution|lower}}/ {{ansible_distribution_release}} nginx"

- name: Install Nginx
  apt: name=nginx update_cache=yes state=installed
  notify: start nginx

- name: Create Nginx configuration file
  template: src=vhost.conf.j2
            dest=/etc/nginx/conf.d/{{ app_name }}.conf
            backup=yes
  notify:
    - reload nginx
    - restart nginx

- name: Ensure that the default site is disabled
  command: rm /etc/nginx/conf.d/default.conf
           removes=/etc/nginx/conf.d/default.conf
  notify:
    - reload nginx
    - restart nginx

- name: Ensure Nginx service is started
  service: name=nginx state=started enabled=yes