---

- name: Install Nginx
  apt: name=nginx update_cache=yes state=installed
  notify: start nginx

- name: Create Nginx configuration file
  template: src=vhost.conf.j2
            dest=/etc/nginx/sites-available/{{ app_name }}
            backup=yes
  notify: reload nginx

- name: Ensure that the default site is disabled
  command: rm /etc/nginx/sites-enabled/default
           removes=/etc/nginx/sites-enabled/default
  notify: reload nginx

- name: Enable application
  command: ln -s /etc/nginx/sites-available/{{ app_name }}
            /etc/nginx/sites-enabled/{{ app_name }}
            creates=/etc/nginx/sites-enabled/{{ app_name }}

- name: Ensure Nginx service is started
  service: name=nginx state=started enabled=yes