application_name: servator
project_name: servator
serve_directory: /serve/

nginx_server_name_servator_re: ~^(?<subdomain>[a-z0-9]+)\.servator\.ws
nginx_server_name_webator_re: ~^servator\.ws www.servator.ws ""

wsgi_app: app:app

git_repo: git@bitbucket.org:janitor/servator.git
git_branch: master