---

- name: Create the application user
  user: name={{ uwsi_user }} state=present

- name: Create the application group
  group: name={{ uwsi_group }} state=present system=yes

- name: Add the application user to the application group
  user: name={{ uwsi_user }} group={{ uwsi_group }} state=present

- name: Ensure uwsgi is installed
  pip: virtualenv={{ virtualenv_path }} name=uwsgi

- name: Create the Gunicorn script file
  template: src=uwsgi.conf.j2
            dest={{ virtualenv_path }}/uwsgi.ini
            owner={{ uwsi_user }}
            group={{ uwsi_group }}
            mode=0755
            backup=yes

- name: Create the application log folder
  file: path={{ application_log_dir }}
        owner={{ uwsi_user }}
        group={{ uwsi_group }}
        mode=0774
        state=directory

- name: Create the application log file
  command: touch {{ application_log_file }}
           creates={{ application_log_file }}

- name: Set permission to the application log file
  file: path={{ application_log_file }}
        owner={{ uwsi_user }}
        group={{ uwsi_group }}
        mode=0664
        state=file

- name: Ensure that the application file permissions are set properly
  file: path={{ virtualenv_path }}
        recurse=yes
        owner={{ uwsi_user }}
        group={{ uwsi_group }}
        state=directory
