---

- name: Create the virtualenv
  command: virtualenv {{ virtualenv_path }} --no-site-packages
           creates={{ virtualenv_path }}/bin/activate

- name: Setup the Git repo
  git: repo={{ git_repo }}
       version="{{ git_branch }}"
       dest={{ project_path }}
       accept_hostkey=yes
  when: setup_git_repo is defined and setup_git_repo
  notify: restart supervisor

- name: Setup project conf
  template: src=conf.py.j2
            dest={{ project_path }}/conf_local.py
            backup=yes
  when: setup_git_repo is defined and setup_git_repo
  notify: restart supervisor

- name: Create serve directory
  file: path={{ serve_directory_path }} state=directory mode=0755

- name: Delete all .pyc files
  command: find . -name '*.pyc' -delete
  args:
    chdir: "{{ project_path }}"

- name: Install packages required
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}
  notify: restart supervisor
