---

- name: Install base packages
  apt: name={{ item }} update_cache=yes force=yes state=installed
  with_items:
    - build-essential
    - ntp
    - htop
    - git
    - libpq-dev
    - python-dev
    - python-pip
    - python-pycurl
    - supervisor
    - zsh
    - vim
    - httpie
    - redis-server

- name: Install virtualenv
  pip: name=virtualenv

- name: Create the application user
  user: name={{ app_user }} state=present

- name: Create the application group
  group: name={{ app_group }} state=present system=yes

- name: Add the application user to the application group
  user: name={{ app_user }} group={{ app_group }} state=present
