---

- name: Install base packages
  apt: name={{ item }} update_cache=yes force=yes state=installed
  with_items:
    - build-essential
    - ntp
    - htop
    - git
    - libpq-dev
    - python-dev
    - python-pip
    - python-pycurl
    - supervisor
    - zsh
    - vim
    - httpie
  tags: packages

- name: Install virtualenv
  pip: name=virtualenv
  tags: packages