---

- name: Install Supervisor
  apt: name=supervisor update_cache=yes state=installed

- name: Create the Supervisor app config file
  template: src=app.conf.j2
            dest=/etc/supervisor/conf.d/{{ app_name }}.conf
            backup=yes
  notify:
    - re-read supervisor conf
